# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e63bba8b0c6cba16cc2a4bda92118b10967cd4f7524f5d3889cd736aced865eace1d76e6618ab76d36c71ebcbb799758491bef652f005b4a7679206012a9db30

test:
  secret_key_base: 5d6fa27c05efe2f8dcc5905f4e0a6661261e9eb4608a25ac794e5d03e24788fd8228dc55f16c9661d596f1e4653772721502fdcd3333f2135496fd9d14035f0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
